### ISSUE TITLE
Make a nice landing page

### ISSUE THREAD

**Issue by JohnathonNow** [NDLUG/ndlug.org#19]
We need a nice home page for the club

**Comment by JohnathonNow** [comment]
We would like a page that we would be proud to show off, because some of the club members felt embarrassed by my previous landing page. qq. Anyways, we would like one that perhaps doesn't list the blog posts, but links to the list. It should show core club info, such as meeting times and locations. We should also have a calendar page, but if it uses google calendar or any other proprietary software I will cry. We also want a page for the IRC chat widget that @cshinaver killed. Perhaps it could also include an enumeration of club resources, such as slack, IRC, appa, a few pis, etc.

**Comment by JohnathonNow** [comment]
Is the current page up to snuff enough to close this issue?

**Comment by pbui** [comment]
Yeah it's fine for now.

**Comment by cshinaver** [comment]
What did I kill
