### ISSUE TITLE
Make a nice theme

### ISSUE THREAD

**Issue by JohnathonNow** [NDLUG/ndlug.org#20]
Probably make one from scratch, that would be smart.

**Comment by JohnathonNow** [comment]
We wanna do some more color scheming @dsmith47

**Comment by bdevorem** [comment]
I vote for a new font.

**Comment by JohnathonNow** [comment]
Is this considered done now, fam? @TBurchfield @pbui

**Comment by TBurchfield** [comment]
Sounds good to me.
